#!/usr/bin/env python3
"""
Code Review Kit - Structured code review workflow with multi-language support.

Usage:
    codereview init --lang go
    codereview review <target>
    codereview analyze <issue-id>
    codereview fix [--issues <ids>]
    codereview report [--format html]
    codereview config
    codereview learn
    codereview auth --platform github
    codereview pr owner/repo 123
"""

import os
import json
import subprocess
from pathlib import Path
from typing import Optional, List
from urllib.parse import urlparse

import typer
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.table import Table
from rich.prompt import Prompt

app = typer.Typer(
    name="codereview",
    help="Code Review Kit - Structured code review workflow with multi-language support",
    add_completion=False,
)

console = Console()

BANNER = r"""
  ____          _     ____                  _ _    _ _   
 / ___|___   __| | __| ___|_ __   ___ _ __ | | | _(_) |_ 
| |   / _ \ / _` |/ _`_  / '_ \ / _ \ '_ \| | |/ / | __|
| |__| (_) | (_| | (_| / /| |_) |  __/ | | | |   <| | |_ 
 \____\___/ \__,_|\__,___|_.__/ \___|_| |_|_|_|\_\_|\__|
"""

TAGLINE = "Code Review Kit - Structured code review workflow"


def show_banner():
    """Display the ASCII art banner."""
    banner_lines = BANNER.strip().split('\n')
    colors = ["bright_blue", "cyan", "bright_cyan", "white", "bright_white"]

    styled_banner = Text()
    for i, line in enumerate(banner_lines):
        color = colors[i % len(colors)]
        styled_banner.append(line + "\n", style=color)

    console.print(styled_banner)
    console.print(f"[italic bright_yellow]{TAGLINE}[/italic bright_yellow]")
    console.print()


@app.command()
def init(
    language: str = typer.Option(None, "--lang", "-l", help="Target language (go, python, kotlin, typescript)"),
    ai: str = typer.Option("claude", "--ai", help="AI assistant to use (claude, gemini, copilot)"),
):
    """Initialize code review kit for a project."""
    show_banner()
    
    # Create .review directory
    review_dir = Path.cwd() / ".review"
    review_dir.mkdir(exist_ok=True)
    
    # Create config file
    config_file = review_dir / "config.yaml"
    if not config_file.exists():
        config_content = f"""# Code Review Kit Configuration
# Generated by: codereview init

language: {language or "auto"}
ai_assistant: {ai}

rules:
  severity_threshold: P2  # P0, P1, P2
  enabled_categories:
    - security
    - performance
    - quality
    - style

output:
  format: markdown
  save_history: true
"""
        config_file.write_text(config_content)
        console.print(f"[green]✓[/green] Created {config_file}")
    
    console.print("[green]✓[/green] Code Review Kit initialized successfully!")
    console.print(f"[dim]Config file: {config_file}[/dim]")


@app.command()
def review(
    target: str = typer.Argument(".", help="Files or directories to review"),
    rules: str = typer.Option("default", "--rules", "-r", help="Rules profile"),
    output: str = typer.Option("markdown", "--output", "-o", help="Output format (markdown, json, html)"),
    language: str = typer.Option(None, "--lang", "-l", help="Override language detection"),
):
    """Run code review on target files."""
    show_banner()
    console.print(f"[cyan]Reviewing:[/cyan] {target}")
    console.print(f"[cyan]Rules:[/cyan] {rules}")
    console.print(f"[cyan]Output:[/cyan] {output}")
    console.print()
    
    # TODO: Implement actual review logic
    console.print("[yellow]Review logic to be implemented...[/yellow]")
    console.print("[dim]Use /codereview.review command in your AI assistant for now.[/dim]")


@app.command()
def analyze(
    issue_id: str = typer.Argument(..., help="Issue ID to analyze"),
    deep: bool = typer.Option(False, "--deep", "-d", help="Deep analysis mode"),
):
    """Deep analyze a specific issue."""
    show_banner()
    console.print(f"[cyan]Analyzing issue:[/cyan] {issue_id}")
    
    if deep:
        console.print("[cyan]Mode:[/cyan] Deep analysis")
    
    console.print()
    console.print("[yellow]Analysis logic to be implemented...[/yellow]")


@app.command()
def fix(
    issues: str = typer.Option("all", "--issues", "-i", help="Issues to fix (all, P0, P1, or comma-separated IDs)"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview without applying"),
):
    """Auto-fix issues where possible."""
    show_banner()
    console.print(f"[cyan]Fixing issues:[/cyan] {issues}")
    
    if dry_run:
        console.print("[cyan]Mode:[/cyan] Dry run (no changes)")
    
    console.print()
    console.print("[yellow]Fix logic to be implemented...[/yellow]")


@app.command()
def report(
    format: str = typer.Option("markdown", "--format", "-f", help="Report format (markdown, html, json)"),
    output_file: str = typer.Option(None, "--output", "-o", help="Output file path"),
):
    """Generate report from last review."""
    show_banner()
    console.print(f"[cyan]Report format:[/cyan] {format}")
    
    if output_file:
        console.print(f"[cyan]Output file:[/cyan] {output_file}")
    
    console.print()
    console.print("[yellow]Report generation to be implemented...[/yellow]")


@app.command()
def config():
    """Open or edit configuration."""
    show_banner()
    
    config_file = Path.cwd() / ".review" / "config.yaml"
    if config_file.exists():
        console.print(f"[green]Config file:[/green] {config_file}")
        console.print(f"[dim]Edit this file to customize your review settings.[/dim]")
    else:
        console.print("[yellow]No config file found. Run 'codereview init' first.[/yellow]")


@app.command()
def learn(
    history_dir: str = typer.Option(".review/results", "--history", "-h", help="History directory"),
):
    """Learn from past reviews to improve rules."""
    show_banner()
    console.print(f"[cyan]Learning from:[/cyan] {history_dir}")
    console.print()
    console.print("[yellow]Learning logic to be implemented...[/yellow]")


@app.command()
def check():
    """Check system requirements and installed tools."""
    show_banner()
    
    console.print("[bold]Checking system requirements...[/bold]\n")
    
    # Check Python
    import sys
    console.print(f"[green]✓[/green] Python {sys.version.split()[0]}")
    
    # Check Git
    import shutil
    if shutil.which("git"):
        console.print("[green]✓[/green] Git installed")
    else:
        console.print("[red]✗[/red] Git not found")
    
    # Check language tools
    tools = {
        "go": ["go", "gofmt"],
        "python": ["python", "pylint", "mypy"],
        "node": ["node", "npm", "eslint"],
    }
    
    console.print("\n[bold]Language tools:[/bold]")
    for lang, tool_list in tools.items():
        found = sum(1 for t in tool_list if shutil.which(t))
        total = len(tool_list)
        if found == total:
            console.print(f"[green]✓[/green] {lang}: {found}/{total} tools")
        elif found > 0:
            console.print(f"[yellow]~[/yellow] {lang}: {found}/{total} tools")
        else:
            console.print(f"[dim]○[/dim] {lang}: not installed")


@app.command()
def scan(
    target: str = typer.Argument(".", help="Target directory to scan"),
    output: str = typer.Option(".review/scanner-results", "--output", "-o", help="Output directory"),
    language: str = typer.Option(None, "--lang", "-l", help="Override language detection"),
    tools: str = typer.Option("all", "--tools", "-t", help="Comma-separated tools or 'all'"),
    auto_install: bool = typer.Option(True, "--install/--no-install", help="Auto-install missing tools"),
):
    """Run integrated code scanning tools with auto-install support."""
    show_banner()
    
    import shutil
    from datetime import datetime
    
    target_path = Path(target).resolve()
    output_path = Path(output)
    output_path.mkdir(parents=True, exist_ok=True)
    
    console.print(f"[cyan]Target:[/cyan] {target_path}")
    
    # Detect language
    if not language:
        language = _detect_language(target_path)
    
    console.print(f"[cyan]Language:[/cyan] {language}")
    console.print(f"[cyan]Auto-install:[/cyan] {'enabled' if auto_install else 'disabled'}")
    console.print()
    
    # Run scanners based on language
    all_issues = []
    
    if language == "go":
        all_issues = _run_go_scanners(target_path, output_path, tools, auto_install)
    elif language == "python":
        all_issues = _run_python_scanners(target_path, output_path, tools, auto_install)
    elif language == "typescript":
        all_issues = _run_typescript_scanners(target_path, output_path, tools, auto_install)
    else:
        console.print(f"[yellow]Warning: Scanner for '{language}' not yet implemented[/yellow]")
        return
    
    # Aggregate and save
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    aggregated_file = output_path / f"aggregated-{timestamp}.json"
    
    result = {
        "timestamp": timestamp,
        "target": str(target_path),
        "language": language,
        "issues": all_issues,
        "summary": {
            "total": len(all_issues),
            "errors": sum(1 for i in all_issues if i.get("severity") in ["error", "critical"]),
            "warnings": sum(1 for i in all_issues if i.get("severity") == "warning"),
            "info": sum(1 for i in all_issues if i.get("severity") in ["info", "note"]),
        }
    }
    
    aggregated_file.write_text(json.dumps(result, indent=2))
    
    # Display summary
    console.print()
    console.print(Panel(
        f"Total: {result['summary']['total']}\n"
        f"Errors: {result['summary']['errors']}\n"
        f"Warnings: {result['summary']['warnings']}\n"
        f"Info: {result['summary']['info']}",
        title="Scan Results",
        border_style="green"
    ))
    
    console.print(f"\n[dim]Results saved to: {aggregated_file}[/dim]")
    console.print("[dim]Use this file with /codereview.pr for comment validation[/dim]")


def _detect_language(target_path: Path) -> str:
    """Detect programming language from project structure."""
    if (target_path / "go.mod").exists():
        return "go"
    if (target_path / "requirements.txt").exists() or (target_path / "pyproject.toml").exists():
        return "python"
    if (target_path / "build.gradle.kts").exists() or (target_path / "build.gradle").exists():
        return "kotlin"
    if (target_path / "package.json").exists() or (target_path / "tsconfig.json").exists():
        return "typescript"
    
    # Check file extensions
    go_count = len(list(target_path.glob("**/*.go")))
    py_count = len(list(target_path.glob("**/*.py")))
    ts_count = len(list(target_path.glob("**/*.ts"))) + len(list(target_path.glob("**/*.tsx")))
    
    counts = {"go": go_count, "python": py_count, "typescript": ts_count}
    if max(counts.values()) > 0:
        return max(counts, key=counts.get)
    
    return "unknown"


def _install_go_tool(tool_name: str) -> bool:
    """Install a Go tool using go install."""
    import subprocess
    
    install_commands = {
        "staticcheck": ["go", "install", "honnef.co/go/tools/cmd/staticcheck@latest"],
        "gosec": ["go", "install", "github.com/securego/gosec/v2/cmd/gosec@latest"],
        "gocognit": ["go", "install", "github.com/uudashr/gocognit/cmd/gocognit@latest"],
        "ineffassign": ["go", "install", "github.com/gordonklaus/ineffassign@latest"],
    }
    
    if tool_name not in install_commands:
        return False
    
    cmd = install_commands[tool_name]
    console.print(f"[yellow]  Installing {tool_name}...[/yellow]")
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode == 0:
            console.print(f"[green]  ✓ {tool_name} installed successfully[/green]")
            return True
        else:
            console.print(f"[red]  ✗ Failed to install {tool_name}: {result.stderr}[/red]")
            return False
    except Exception as e:
        console.print(f"[red]  ✗ Error installing {tool_name}: {e}[/red]")
        return False


def _install_python_tool(tool_name: str) -> bool:
    """Install a Python tool using pip."""
    import subprocess
    
    install_commands = {
        "pylint": ["pip", "install", "pylint"],
        "mypy": ["pip", "install", "mypy"],
        "flake8": ["pip", "install", "flake8"],
        "ruff": ["pip", "install", "ruff"],
        "bandit": ["pip", "install", "bandit"],
    }
    
    if tool_name not in install_commands:
        return False
    
    cmd = install_commands[tool_name]
    console.print(f"[yellow]  Installing {tool_name}...[/yellow]")
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode == 0:
            console.print(f"[green]  ✓ {tool_name} installed successfully[/green]")
            return True
        else:
            console.print(f"[red]  ✗ Failed to install {tool_name}: {result.stderr}[/red]")
            return False
    except Exception as e:
        console.print(f"[red]  ✗ Error installing {tool_name}: {e}[/red]")
        return False


def _check_tool_with_install(tool_name: str, language: str, auto_install: bool = True) -> bool:
    """Check if tool exists, optionally install if missing."""
    import shutil
    
    if shutil.which(tool_name):
        return True
    
    if not auto_install:
        return False
    
    if language == "go":
        return _install_go_tool(tool_name)
    elif language == "python":
        return _install_python_tool(tool_name)
    
    return False


def _run_go_scanners(target_path: Path, output_path: Path, tools_filter: str, auto_install: bool = True) -> List[dict]:
    """Run Go scanning tools with auto-install support."""
    import shutil
    import subprocess
    
    issues = []
    
    # Tool configurations: (tool_name, display_name, cmd, severity, needs_install)
    go_tools = [
        ("go", "go build", ["go", "build", "./..."], "P0", False),
        ("go", "go vet", ["go", "vet", "./..."], "P1", False),
        ("staticcheck", "staticcheck", ["staticcheck", "-f", "json", "./..."], "P1", True),
        ("gosec", "gosec", ["gosec", "-fmt", "json", "./..."], "P0", True),
    ]
    
    # Check if Go is installed first
    if not shutil.which("go"):
        console.print("[red]  Go is not installed. Please install Go first.[/red]")
        return issues
    
    for tool_name, display_name, cmd, severity, needs_install in go_tools:
        if tools_filter != "all" and tool_name not in tools_filter.split(","):
            continue
        
        # Check/install tool
        if tool_name == "go":
            # go is built-in, check if available
            if not shutil.which("go"):
                console.print(f"[red]  [{display_name}] Go not found[/red]")
                continue
        elif not _check_tool_with_install(tool_name, "go", auto_install):
            console.print(f"[yellow]  [{display_name}] Not available (install failed)[/yellow]")
            continue
        
        console.print(f"[cyan]  [{display_name}] Running...[/cyan]")
        
        try:
            result = subprocess.run(
                cmd,
                cwd=target_path,
                capture_output=True,
                text=True,
                timeout=300
            )
            
            # Parse output
            if result.stdout:
                try:
                    if tool_name == "staticcheck" or tool_name == "gosec":
                        # JSON output
                        for line in result.stdout.strip().split("\n"):
                            if line.strip():
                                try:
                                    data = json.loads(line)
                                    issues.append({
                                        "tool": tool_name,
                                        "file": data.get("location", {}).get("file", ""),
                                        "line": data.get("location", {}).get("line", 0),
                                        "severity": severity.lower() if severity == "P0" else "warning",
                                        "message": data.get("message", ""),
                                        "rule": data.get("code", data.get("rule", "")),
                                    })
                                except json.JSONDecodeError:
                                    pass
                except Exception as e:
                    console.print(f"[yellow]  Warning: Could not parse {tool_name} output[/yellow]")
            
            if result.stderr and tool_name in ["go", "staticcheck"]:
                # Parse error output for go build/vet
                for line in result.stderr.split("\n"):
                    if ":" in line:
                        parts = line.split(":")
                        if len(parts) >= 3:
                            issues.append({
                                "tool": tool_name,
                                "file": parts[0].strip(),
                                "line": int(parts[1].strip()) if parts[1].strip().isdigit() else 0,
                                "severity": "error",
                                "message": ":".join(parts[2:]).strip(),
                                "rule": "",
                            })
        
        except subprocess.TimeoutExpired:
            console.print(f"[red]  [{display_name}] Timeout[/red]")
        except Exception as e:
            console.print(f"[red]  [{display_name}] Error: {e}[/red]")
    
    return issues


def _run_python_scanners(target_path: Path, output_path: Path, tools_filter: str, auto_install: bool = True) -> List[dict]:
    """Run Python scanning tools with auto-install support."""
    import shutil
    import subprocess
    
    issues = []
    
    # Tool configurations: (tool_name, display_name, cmd_base, severity)
    py_tools = [
        ("pylint", "pylint", ["pylint", "--output-format=json"], "P1"),
        ("mypy", "mypy", ["mypy", "--output", "json"], "P1"),
        ("flake8", "flake8", ["flake8", "--format=json"], "P2"),
        ("ruff", "ruff", ["ruff", "check", "--output-format", "json"], "P1"),
        ("bandit", "bandit", ["bandit", "-f", "json", "-r"], "P0"),
    ]
    
    # Check if Python/pip is installed
    if not shutil.which("pip") and not shutil.which("pip3"):
        console.print("[red]  pip is not installed. Please install Python/pip first.[/red]")
        return issues
    
    for tool_name, display_name, cmd_base, severity in py_tools:
        if tools_filter != "all" and tool_name not in tools_filter.split(","):
            continue
        
        # Check/install tool
        if not _check_tool_with_install(tool_name, "python", auto_install):
            console.print(f"[yellow]  [{display_name}] Not available[/yellow]")
            continue
        
        console.print(f"[cyan]  [{display_name}] Running...[/cyan]")
        
        cmd = cmd_base + [str(target_path)]
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300
            )
            
            if result.stdout:
                try:
                    data = json.loads(result.stdout)
                    if isinstance(data, list):
                        for item in data:
                            issues.append({
                                "tool": tool_name,
                                "file": item.get("path", item.get("file", "")),
                                "line": item.get("line", item.get("lineNumber", 0)),
                                "severity": severity.lower() if severity == "P0" else "warning",
                                "message": item.get("message", item.get("msg", "")),
                                "rule": item.get("code", item.get("symbol", "")),
                            })
                except json.JSONDecodeError:
                    pass
        
        except Exception as e:
            console.print(f"[red]  [{display_name}] Error: {e}[/red]")
    
    return issues


def _run_typescript_scanners(target_path: Path, output_path: Path, tools_filter: str) -> List[dict]:
    """Run TypeScript scanning tools."""
    import shutil
    import subprocess
    
    issues = []
    
    ts_tools = [
        ("tsc", "TypeScript", ["npx", "tsc", "--noEmit", "--pretty", "false"], "P0"),
        ("eslint", "ESLint", ["npx", "eslint", "--format", "json"], "P1"),
    ]
    
    for tool_name, display_name, cmd_base, severity in ts_tools:
        if tools_filter != "all" and tool_name not in tools_filter.split(","):
            continue
        
        console.print(f"[cyan]  [{display_name}] Running...[/cyan]")
        
        cmd = cmd_base + [str(target_path)]
        
        try:
            result = subprocess.run(
                cmd,
                cwd=target_path,
                capture_output=True,
                text=True,
                timeout=300
            )
            
            if result.stdout:
                if tool_name == "eslint":
                    try:
                        data = json.loads(result.stdout)
                        for file_result in data:
                            for msg in file_result.get("messages", []):
                                issues.append({
                                    "tool": "eslint",
                                    "file": file_result.get("filePath", ""),
                                    "line": msg.get("line", 0),
                                    "severity": msg.get("severity", 1) == 2 and "error" or "warning",
                                    "message": msg.get("message", ""),
                                    "rule": msg.get("ruleId", ""),
                                })
                    except json.JSONDecodeError:
                        pass
                else:
                    # tsc output
                    for line in result.stdout.split("\n"):
                        if "error TS" in line:
                            issues.append({
                                "tool": "tsc",
                                "file": "",
                                "line": 0,
                                "severity": "error",
                                "message": line.strip(),
                                "rule": "",
                            })
        
        except Exception as e:
            console.print(f"[red]  [{display_name}] Error: {e}[/red]")
    
    return issues


@app.command()
def auth(
    platform: str = typer.Option(None, "--platform", "-p", help="Platform (github, gitlab, gitee)"),
    token: str = typer.Option(None, "--token", "-t", help="API token (will prompt if not provided)"),
    host: str = typer.Option(None, "--host", "-h", help="Host URL (for self-hosted GitLab)"),
    list_tokens: bool = typer.Option(False, "--list", "-l", help="List configured tokens"),
):
    """Configure authentication for remote repositories."""
    show_banner()
    
    review_dir = Path.cwd() / ".review"
    review_dir.mkdir(exist_ok=True)
    auth_file = review_dir / "auth.yaml"
    
    if list_tokens:
        _list_auth_config(auth_file)
        return
    
    # Platform selection
    if not platform:
        platform = Prompt.ask(
            "Select platform",
            choices=["github", "gitlab", "gitee"],
            default="github"
        )
    
    # Token input
    if not token:
        token = Prompt.ask(
            f"Enter {platform.upper()} token",
            password=True
        )
    
    # Validate and save
    _save_auth_config(auth_file, platform, token, host)
    
    # Validate token
    _validate_token(platform, token, host)
    
    console.print(f"[green]✓[/green] Authentication configured for {platform}")
    console.print(f"[dim]Token saved to: {auth_file}[/dim]")


def _list_auth_config(auth_file: Path):
    """List configured authentication."""
    if not auth_file.exists():
        console.print("[yellow]No authentication configured.[/yellow]")
        return
    
    import yaml
    config = yaml.safe_load(auth_file.read_text()) or {}
    
    table = Table(title="Configured Authentication")
    table.add_column("Platform")
    table.add_column("Host")
    table.add_column("Token Status")
    
    for platform, settings in config.items():
        host = settings.get("host", "default")
        token = settings.get("token", "")
        status = "✓ Configured" if token else "✗ Missing"
        table.add_row(platform, host, status)
    
    console.print(table)


def _save_auth_config(auth_file: Path, platform: str, token: str, host: Optional[str]):
    """Save authentication configuration."""
    import yaml
    
    config = {}
    if auth_file.exists():
        config = yaml.safe_load(auth_file.read_text()) or {}
    
    config[platform] = {
        "token": token,
    }
    if host:
        config[platform]["host"] = host
    
    auth_file.write_text(yaml.dump(config, default_flow_style=False))
    
    # Ensure auth.yaml is in .gitignore
    gitignore = Path.cwd() / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text()
        if ".review/auth.yaml" not in content:
            gitignore.write_text(content + "\n# Code Review Kit auth\n.review/auth.yaml\n")
    else:
        gitignore.write_text("# Code Review Kit auth\n.review/auth.yaml\n")


def _validate_token(platform: str, token: str, host: Optional[str]):
    """Validate token by making a test API call."""
    import httpx
    
    try:
        if platform == "github":
            resp = httpx.get(
                "https://api.github.com/user",
                headers={"Authorization": f"token {token}"},
                timeout=10
            )
            if resp.status_code == 200:
                user = resp.json()
                console.print(f"[green]✓[/green] Authenticated as: {user.get('login', 'unknown')}")
            else:
                console.print(f"[red]✗[/red] Token validation failed: {resp.status_code}")
        
        elif platform == "gitlab":
            base_url = host or "https://gitlab.com"
            resp = httpx.get(
                f"{base_url}/api/v4/user",
                headers={"PRIVATE-TOKEN": token},
                timeout=10
            )
            if resp.status_code == 200:
                user = resp.json()
                console.print(f"[green]✓[/green] Authenticated as: {user.get('username', 'unknown')}")
            else:
                console.print(f"[red]✗[/red] Token validation failed: {resp.status_code}")
        
        elif platform == "gitee":
            resp = httpx.get(
                "https://gitee.com/api/v5/user",
                params={"access_token": token},
                timeout=10
            )
            if resp.status_code == 200:
                user = resp.json()
                console.print(f"[green]✓[/green] Authenticated as: {user.get('login', 'unknown')}")
            else:
                console.print(f"[red]✗[/red] Token validation failed: {resp.status_code}")
    
    except Exception as e:
        console.print(f"[yellow]Warning: Could not validate token: {e}[/yellow]")


@app.command()
def pr(
    repo: str = typer.Argument(None, help="Repository (owner/repo) or PR URL"),
    pr_number: int = typer.Argument(None, help="PR/MR number"),
    analyze: bool = typer.Option(True, "--analyze/--no-analyze", help="Analyze comments with AI"),
    include_approved: bool = typer.Option(False, "--include-approved", help="Include approved PRs"),
):
    """Analyze pull/merge request comments."""
    show_banner()
    
    # Parse input
    if repo and "/" in repo and not pr_number:
        # Could be a full PR URL or "owner/repo#123" format
        if repo.startswith("http"):
            repo, pr_number = _parse_pr_url(repo)
        elif "#" in repo:
            repo, pr_number = repo.split("#")
            pr_number = int(pr_number)
    
    if not repo or not pr_number:
        # Try to detect from git remote
        repo = _detect_repo_from_git()
        if not repo:
            console.print("[red]Error: Could not determine repository.[/red]")
            console.print("Usage: codereview pr owner/repo 123")
            raise typer.Exit(1)
        
        if not pr_number:
            pr_number = Prompt.ask("Enter PR number", type=int)
    
    console.print(f"[cyan]Repository:[/cyan] {repo}")
    console.print(f"[cyan]PR Number:[/cyan] #{pr_number}")
    console.print()
    
    # Get authentication
    platform, token, host = _get_auth_for_repo(repo)
    if not token:
        console.print("[red]Error: No authentication configured.[/red]")
        console.print("Run 'codereview auth --platform github' first.")
        raise typer.Exit(1)
    
    # Fetch PR data
    pr_data = _fetch_pr_data(platform, repo, pr_number, token, host)
    
    if not pr_data:
        console.print("[red]Error: Could not fetch PR data.[/red]")
        raise typer.Exit(1)
    
    # Display PR info
    _display_pr_info(pr_data)
    
    # Fetch and analyze comments
    comments = _fetch_pr_comments(platform, repo, pr_number, token, host)
    
    if analyze and comments:
        _analyze_comments(comments, pr_data)


def _parse_pr_url(url: str) -> tuple:
    """Parse PR URL to extract repo and PR number."""
    # https://github.com/owner/repo/pull/123
    parsed = urlparse(url)
    path_parts = parsed.path.strip("/").split("/")
    
    if "pull" in path_parts:
        idx = path_parts.index("pull")
        repo = "/".join(path_parts[:idx])
        pr_number = int(path_parts[idx + 1])
        return repo, pr_number
    elif "merge_requests" in path_parts:
        idx = path_parts.index("merge_requests")
        repo = "/".join(path_parts[:idx])
        pr_number = int(path_parts[idx + 1])
        return repo, pr_number
    
    return None, None


def _detect_repo_from_git() -> Optional[str]:
    """Detect repository from git remote."""
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            # Parse git URL
            # git@github.com:owner/repo.git
            # https://github.com/owner/repo.git
            if "github.com" in url:
                parts = url.split("github.com")[-1].strip(":/").replace(".git", "")
                return parts
            elif "gitlab.com" in url:
                parts = url.split("gitlab.com")[-1].strip(":/").replace(".git", "")
                return parts
            elif "gitee.com" in url:
                parts = url.split("gitee.com")[-1].strip(":/").replace(".git", "")
                return parts
    except Exception:
        pass
    return None


def _get_auth_for_repo(repo: str) -> tuple:
    """Get authentication for a repository."""
    import yaml
    
    # Check environment variables first
    if "GITHUB_TOKEN" in os.environ:
        return "github", os.environ["GITHUB_TOKEN"], None
    if "GITLAB_TOKEN" in os.environ:
        return "gitlab", os.environ["GITLAB_TOKEN"], None
    if "GITEE_TOKEN" in os.environ:
        return "gitee", os.environ["GITEE_TOKEN"], None
    
    # Check auth file
    auth_file = Path.cwd() / ".review" / "auth.yaml"
    if auth_file.exists():
        config = yaml.safe_load(auth_file.read_text()) or {}
        
        # Try to detect platform from repo or git remote
        git_url = _detect_repo_from_git()
        if git_url:
            if "github" in str(git_url) or "github" in repo:
                platform = "github"
            elif "gitlab" in str(git_url) or "gitlab" in repo:
                platform = "gitlab"
            elif "gitee" in str(git_url) or "gitee" in repo:
                platform = "gitee"
            else:
                platform = "github"  # default
        else:
            platform = "github"
        
        if platform in config:
            return platform, config[platform].get("token"), config[platform].get("host")
    
    return None, None, None


def _fetch_pr_data(platform: str, repo: str, pr_number: int, token: str, host: Optional[str]) -> Optional[dict]:
    """Fetch PR data from API."""
    import httpx
    
    try:
        if platform == "github":
            resp = httpx.get(
                f"https://api.github.com/repos/{repo}/pulls/{pr_number}",
                headers={"Authorization": f"token {token}"},
                timeout=30
            )
            if resp.status_code == 200:
                return resp.json()
        
        elif platform == "gitlab":
            base_url = host or "https://gitlab.com"
            # GitLab uses URL-encoded project ID
            import urllib.parse
            project_id = urllib.parse.quote(repo, safe='')
            resp = httpx.get(
                f"{base_url}/api/v4/projects/{project_id}/merge_requests/{pr_number}",
                headers={"PRIVATE-TOKEN": token},
                timeout=30
            )
            if resp.status_code == 200:
                return resp.json()
        
        elif platform == "gitee":
            owner, project = repo.split("/")
            resp = httpx.get(
                f"https://gitee.com/api/v5/repos/{owner}/{project}/pulls/{pr_number}",
                params={"access_token": token},
                timeout=30
            )
            if resp.status_code == 200:
                return resp.json()
    
    except Exception as e:
        console.print(f"[red]Error fetching PR: {e}[/red]")
    
    return None


def _fetch_pr_comments(platform: str, repo: str, pr_number: int, token: str, host: Optional[str]) -> List[dict]:
    """Fetch PR comments from API."""
    import httpx
    
    comments = []
    
    try:
        if platform == "github":
            # Review comments (inline)
            resp = httpx.get(
                f"https://api.github.com/repos/{repo}/pulls/{pr_number}/comments",
                headers={"Authorization": f"token {token}"},
                timeout=30
            )
            if resp.status_code == 200:
                comments.extend([{"type": "review", **c} for c in resp.json()])
            
            # Issue comments (general)
            resp = httpx.get(
                f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments",
                headers={"Authorization": f"token {token}"},
                timeout=30
            )
            if resp.status_code == 200:
                comments.extend([{"type": "issue", **c} for c in resp.json()])
            
            # Reviews
            resp = httpx.get(
                f"https://api.github.com/repos/{repo}/pulls/{pr_number}/reviews",
                headers={"Authorization": f"token {token}"},
                timeout=30
            )
            if resp.status_code == 200:
                comments.extend([{"type": "review_summary", **c} for c in resp.json()])
        
        elif platform == "gitlab":
            base_url = host or "https://gitlab.com"
            import urllib.parse
            project_id = urllib.parse.quote(repo, safe='')
            
            resp = httpx.get(
                f"{base_url}/api/v4/projects/{project_id}/merge_requests/{pr_number}/notes",
                headers={"PRIVATE-TOKEN": token},
                timeout=30
            )
            if resp.status_code == 200:
                comments.extend([{"type": "note", **c} for c in resp.json()])
        
        elif platform == "gitee":
            owner, project = repo.split("/")
            resp = httpx.get(
                f"https://gitee.com/api/v5/repos/{owner}/{project}/pulls/{pr_number}/comments",
                params={"access_token": token},
                timeout=30
            )
            if resp.status_code == 200:
                comments.extend([{"type": "comment", **c} for c in resp.json()])
    
    except Exception as e:
        console.print(f"[yellow]Warning: Error fetching comments: {e}[/yellow]")
    
    console.print(f"[green]✓[/green] Fetched {len(comments)} comments")
    return comments


def _display_pr_info(pr_data: dict):
    """Display PR information."""
    table = Table(show_header=False, box=None)
    table.add_column("Key", style="cyan")
    table.add_column("Value")
    
    table.add_row("Title", pr_data.get("title", "N/A"))
    table.add_row("Author", pr_data.get("user", {}).get("login", "N/A"))
    table.add_row("State", pr_data.get("state", "N/A"))
    table.add_row("Created", pr_data.get("created_at", "N/A")[:10] if pr_data.get("created_at") else "N/A")
    table.add_row("Additions", f"+{pr_data.get('additions', 0)}")
    table.add_row("Deletions", f"-{pr_data.get('deletions', 0)}")
    table.add_row("Changed Files", str(pr_data.get("changed_files", 0)))
    
    console.print(Panel(table, title="PR Information", border_style="cyan"))


def _analyze_comments(comments: List[dict], pr_data: dict):
    """Analyze comments with interactive fix/reply workflow."""
    from datetime import datetime
    
    # Load scanner results if available
    scanner_results = _load_scanner_results()
    if scanner_results:
        console.print(f"[cyan]已加载 {len(scanner_results)} 条扫描结果[/cyan]\n")
    
    # Filter actionable comments (exclude approvals and bot comments)
    actionable_keywords = ["bug", "error", "crash", "security", "vulnerability", 
                          "performance", "slow", "suggest", "consider", "should",
                          "must", "need", "fix", "change", "incorrect", "wrong"]
    approval_keywords = ["lgtm", "looks good", "approved", "👍", "merge", "ship"]
    
    actionable_comments = []
    for comment in comments:
        body = comment.get("body", "").lower()
        user = comment.get("user", {}).get("login", "")
        
        # Skip bot comments
        if "bot" in user.lower() or "[bot]" in user:
            continue
        
        # Skip approval comments
        if any(kw in body for kw in approval_keywords):
            continue
        
        # Check if actionable
        if any(kw in body for kw in actionable_keywords) or "?" in body:
            actionable_comments.append(comment)
    
    if not actionable_comments:
        console.print("[green]✓[/green] No actionable comments found. PR looks good!")
        return
    
    console.print(f"\n[bold]发现 {len(actionable_comments)} 条待处理评论[/bold]\n")
    
    # Process each comment interactively
    pending_fixes = []
    pending_replies = []
    
    for i, comment in enumerate(actionable_comments, 1):
        result = _process_single_comment(comment, i, len(actionable_comments), scanner_results)
        if result:
            if result["action"] == "fix":
                pending_fixes.append(result)
            elif result["action"] == "reply":
                pending_replies.append(result)
    
    # Summary
    console.print("\n" + "=" * 60)
    console.print("[bold]处理汇总[/bold]")
    console.print(f"  待修复: {len(pending_fixes)} 条")
    console.print(f"  待回复: {len(pending_replies)} 条")
    
    # Save pending items
    review_dir = Path.cwd() / ".review" / "results"
    review_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    pr_num = pr_data.get('number', 'unknown')
    
    # Save pending fixes
    if pending_fixes:
        fix_file = review_dir / f"pr-{pr_num}-fixes-{timestamp}.json"
        fix_file.write_text(json.dumps({
            "pr": {"number": pr_num, "title": pr_data.get("title")},
            "fixes": pending_fixes,
            "created": timestamp
        }, indent=2, default=str))
        console.print(f"\n[dim]修复方案已保存: {fix_file}[/dim]")
    
    # Save pending replies
    if pending_replies:
        reply_file = review_dir / f"pr-{pr_num}-replies-{timestamp}.json"
        reply_file.write_text(json.dumps({
            "pr": {"number": pr_num, "title": pr_data.get("title")},
            "replies": pending_replies,
            "created": timestamp
        }, indent=2, default=str))
        console.print(f"[dim]回复方案已保存: {reply_file}[/dim]")
    
    console.print("\n[bold]下一步:[/bold]")
    if pending_fixes:
        console.print("  1. 运行 [cyan]/codereview.fix[/cyan] 应用修复方案")
        console.print("     (工具会先检查为何未自动检测，再执行修复)")
    if pending_replies:
        console.print("  2. 运行 [cyan]/codereview.reply[/cyan] 发送回复")


def _load_scanner_results() -> List[dict]:
    """Load the most recent scanner results."""
    scanner_dir = Path.cwd() / ".review" / "scanner-results"
    
    if not scanner_dir.exists():
        return []
    
    # Find the most recent aggregated file
    aggregated_files = sorted(scanner_dir.glob("aggregated-*.json"), reverse=True)
    
    if not aggregated_files:
        return []
    
    try:
        data = json.loads(aggregated_files[0].read_text())
        return data.get("issues", [])
    except Exception:
        return []


def _process_single_comment(comment: dict, index: int, total: int, scanner_results: Optional[List[dict]] = None) -> Optional[dict]:
    """Process a single comment interactively."""
    from rich.markdown import Markdown
    
    body = comment.get("body", "")
    user = comment.get("user", {}).get("login", "unknown")
    location = comment.get("path", "")
    line = comment.get("line", comment.get("original_line", ""))
    
    # Display comment
    console.print(f"\n[bold cyan]═══ 评论 {index}/{total} ═══[/bold cyan]")
    console.print(f"[dim]评论者: {user}[/dim]")
    if location:
        console.print(f"[dim]位置: {location}:{line}[/dim]")
    console.print(f"\n{body}")
    
    # Analyze comment with scanner results
    analysis = _analyze_comment_validity(comment, scanner_results)
    
    console.print(f"\n[bold]分析结果:[/bold] {analysis['status']}")
    console.print(f"[dim]原因: {analysis['reason']}[/dim]")
    
    # Show solution preview
    console.print(f"\n[bold]建议方案:[/bold]")
    console.print(Panel(analysis["solution_preview"], border_style="green"))
    
    # User action
    console.print("\n[bold]请选择操作:[/bold]")
    console.print("  [1] 确认方案")
    console.print("  [2] 查看详细方案")
    console.print("  [3] 编辑方案")
    console.print("  [4] 跳过")
    console.print("  [5] 标记为需要讨论")
    
    choice = Prompt.ask("选择", choices=["1", "2", "3", "4", "5"], default="1")
    
    if choice == "1":
        return {
            "comment_id": comment.get("id"),
            "comment_body": body,
            "user": user,
            "location": f"{location}:{line}" if location else None,
            "action": "fix" if analysis["is_correct"] else "reply",
            "solution": analysis["solution"],
            "reason": analysis["reason"],
            "tool_check": analysis.get("tool_check")
        }
    elif choice == "2":
        # Show detailed solution
        console.print(Panel(analysis["solution"], title="详细方案", border_style="cyan"))
        if Prompt.ask("确认此方案?", choices=["y", "n"], default="y") == "y":
            return {
                "comment_id": comment.get("id"),
                "comment_body": body,
                "user": user,
                "location": f"{location}:{line}" if location else None,
                "action": "fix" if analysis["is_correct"] else "reply",
                "solution": analysis["solution"],
                "reason": analysis["reason"],
                "tool_check": analysis.get("tool_check")
            }
    elif choice == "3":
        # Edit solution
        console.print("[dim]请输入修改后的方案 (输入完成后按 Ctrl+Z 然后回车):[/dim]")
        lines = []
        try:
            while True:
                line_input = input()
                lines.append(line_input)
        except EOFError:
            pass
        custom_solution = "\n".join(lines)
        return {
            "comment_id": comment.get("id"),
            "comment_body": body,
            "user": user,
            "location": f"{location}:{line}" if location else None,
            "action": "fix" if analysis["is_correct"] else "reply",
            "solution": custom_solution or analysis["solution"],
            "reason": analysis["reason"],
            "tool_check": analysis.get("tool_check")
        }
    elif choice == "5":
        return {
            "comment_id": comment.get("id"),
            "comment_body": body,
            "user": user,
            "action": "discuss",
            "solution": "需要团队讨论"
        }
    
    return None


def _find_matching_scanner_issue(comment: dict, scanner_results: List[dict]) -> Optional[dict]:
    """Find a matching issue from scanner results for a comment."""
    comment_path = comment.get("path", "")
    comment_line = comment.get("line", comment.get("original_line", 0))
    
    for issue in scanner_results:
        # Match by file path and line number
        issue_file = issue.get("file", "")
        issue_line = issue.get("line", 0)
        
        # Normalize paths for comparison
        if comment_path and issue_file:
            # Check if paths match (handle relative vs absolute)
            comment_path_norm = comment_path.replace("\\", "/")
            issue_file_norm = issue_file.replace("\\", "/")
            
            if comment_path_norm.endswith(issue_file_norm) or issue_file_norm.endswith(comment_path_norm):
                # Check line number (allow some tolerance)
                if abs(comment_line - issue_line) <= 2:
                    return issue
    
    return None


def _analyze_comment_validity(comment: dict, scanner_results: Optional[List[dict]] = None) -> dict:
    """
    Analyze if a comment is correct and generate solution.
    
    Args:
        comment: The PR comment to analyze
        scanner_results: Optional list of scanner issues to check against
    
    Returns:
        {
            "is_correct": bool,
            "status": str,  # "✅ 评论正确" or "❌ 评论不正确"
            "reason": str,
            "solution_preview": str,
            "solution": str,
            "tool_check": dict  # Only for correct comments
        }
    """
    body = comment.get("body", "").lower()
    location = comment.get("path", "")
    line = comment.get("line", comment.get("original_line", 0))
    
    # Initialize scanner_results if not provided
    if scanner_results is None:
        scanner_results = []
    
    # Check if scanner detected this issue
    scanner_match = _find_matching_scanner_issue(comment, scanner_results)
    
    # Heuristics for common patterns
    # In real implementation, this would use AI to analyze
    
    # Security issues - usually correct
    if any(kw in body for kw in ["sql injection", "xss", "vulnerability", "security"]):
        if scanner_match:
            return {
                "is_correct": True,
                "status": "✅ 评论正确 (工具已检测)",
                "reason": f"安全问题是真实存在的，工具 [{scanner_match.get('tool', 'unknown')}] 已检测到此问题",
                "solution_preview": "使用参数化查询/输入验证/转义处理",
                "solution": f"""## 修复方案

### 问题
{comment.get('body', '')}

### 工具检测结果
- 工具: {scanner_match.get('tool', 'unknown')}
- 规则: {scanner_match.get('rule', 'N/A')}
- 严重程度: {scanner_match.get('severity', 'unknown')}

### 修复建议
使用安全的编码实践修复此安全问题。

### 代码修改
```diff
- // 存在安全问题的代码
+ // 修复后的代码
```
""",
                "tool_check": {
                    "detected": True,
                    "tool": scanner_match.get("tool"),
                    "rule": scanner_match.get("rule"),
                    "reason": "工具已检测到此问题"
                }
            }
        else:
            return {
                "is_correct": True,
                "status": "✅ 评论正确",
                "reason": "安全问题是真实存在的，需要进行修复",
                "solution_preview": "使用参数化查询/输入验证/转义处理",
                "solution": f"""## 修复方案

### 问题
{comment.get('body', '')}

### 修复建议
使用安全的编码实践修复此安全问题。

### 代码修改
```diff
- // 存在安全问题的代码
+ // 修复后的代码
```

### 工具自检
- 当前工具未检测到此问题
- 建议新增安全规则以自动检测此类问题
""",
                "tool_check": {
                    "detected": False,
                    "reason": "当前工具未包含此模式检测",
                    "suggestion": "新增安全扫描规则或使用专用安全工具 (gosec, bandit)"
                }
            }
    
    # Performance issues - usually correct
    if any(kw in body for kw in ["n+1", "slow", "performance", "optimize"]):
        if scanner_match:
            return {
                "is_correct": True,
                "status": "✅ 评论正确 (工具已检测)",
                "reason": f"性能问题确实存在，工具 [{scanner_match.get('tool', 'unknown')}] 已检测到",
                "solution_preview": "优化查询/添加索引/使用缓存",
                "solution": f"""## 修复方案

### 问题
{comment.get('body', '')}

### 工具检测结果
- 工具: {scanner_match.get('tool', 'unknown')}
- 规则: {scanner_match.get('rule', 'N/A')}

### 修复建议
优化代码以提升性能。
""",
                "tool_check": {
                    "detected": True,
                    "tool": scanner_match.get("tool"),
                    "rule": scanner_match.get("rule"),
                    "reason": "工具已检测到此问题"
                }
            }
        else:
            return {
                "is_correct": True,
                "status": "✅ 评论正确",
                "reason": "性能问题确实存在，优化可以提升系统性能",
                "solution_preview": "优化查询/添加索引/使用缓存",
                "solution": f"""## 修复方案

### 问题
{comment.get('body', '')}

### 修复建议
优化代码以提升性能。

### 工具自检
- 静态分析工具未检测到此性能问题
- 性能问题通常需要运行时分析或专门的性能工具
""",
                "tool_check": {
                    "detected": False,
                    "reason": "性能问题需要运行时分析",
                    "suggestion": "考虑使用性能分析工具 (pprof, py-spy)"
                }
            }
    
    # Style/Naming issues - check against scanner results
    if any(kw in body for kw in ["naming", "style", "format", "indent"]):
        if scanner_match:
            # Scanner detected a style issue - it's valid
            return {
                "is_correct": True,
                "status": "✅ 评论正确 (工具已检测)",
                "reason": f"代码风格问题确实存在，工具 [{scanner_match.get('tool', 'unknown')}] 已检测到",
                "solution_preview": "根据工具建议修复风格问题",
                "solution": f"""## 修复方案

### 问题
{comment.get('body', '')}

### 工具检测结果
- 工具: {scanner_match.get('tool', 'unknown')}
- 规则: {scanner_match.get('rule', 'N/A')}

### 修复建议
根据工具和评论者的建议修复风格问题。
""",
                "tool_check": {
                    "detected": True,
                    "tool": scanner_match.get("tool"),
                    "rule": scanner_match.get("rule"),
                    "reason": "工具已检测到此问题"
                }
            }
        else:
            # No scanner match - could be a matter of preference
            return {
                "is_correct": False,
                "status": "❌ 评论不正确",
                "reason": "命名风格符合当前语言/项目的规范，评论者的建议不适用",
                "solution_preview": "解释当前命名符合规范，提供参考文档",
                "solution": f"""## 回复方案

### 为什么评论不正确
感谢您的审查！关于命名规范的问题：

根据项目的编码规范，当前命名方式是正确的。
工具扫描也未发现风格问题。

### 支持证据
- 项目编码规范文档
- 语言官方风格指南

### 回复草稿
> 感谢您的审查！关于命名规范的问题，
> 
> 当前的命名方式符合项目规范。
> 
> 参考：[编码规范文档链接]
"""
        }
    
    # Questions - need clarification
    if "?" in body or any(kw in body for kw in ["why", "how", "what"]):
        return {
            "is_correct": False,
            "status": "ℹ️ 需要回复",
            "reason": "这是一个问题，需要提供解释或澄清",
            "solution_preview": "提供详细的解释和技术背景",
            "solution": f"""## 回复方案

### 问题
{comment.get('body', '')}

### 回复草稿
> 感谢您的问题！
> 
> [在此提供详细解释]
> 
> 如果您还有其他问题，请随时提出。
"""
        }
    
    # Default: assume correct and provide fix
    return {
        "is_correct": True,
        "status": "✅ 评论正确",
        "reason": "评论指出的问题确实存在",
        "solution_preview": "根据评论建议进行代码修改",
        "solution": f"""## 修复方案

### 问题
{comment.get('body', '')}

### 修复建议
根据评论者的建议进行修改。

### 工具自检
- 检查是否有对应规则
- 评估是否需要新增规则
""",
        "tool_check": {
            "detected": False,
            "reason": "需要进一步分析",
            "suggestion": "评估规则库完整性"
        }
    }


@app.command()
def reply(
    reply_file: str = typer.Argument(None, help="Reply file path or 'latest' for most recent"),
    comment_id: str = typer.Option(None, "--comment", "-c", help="Specific comment ID to reply"),
    all_pending: bool = typer.Option(False, "--all", "-a", help="Reply to all pending comments"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview without sending"),
):
    """Reply to PR/MR comments with generated responses."""
    show_banner()
    
    review_dir = Path.cwd() / ".review" / "results"
    
    # Find reply file
    if reply_file == "latest" or not reply_file:
        reply_files = sorted(review_dir.glob("pr-*-replies-*.json"), reverse=True)
        if not reply_files:
            console.print("[red]Error: No pending replies found.[/red]")
            console.print("Run 'codereview pr' first to analyze comments.")
            raise typer.Exit(1)
        reply_file = str(reply_files[0])
    
    file_path = Path(reply_file)
    if not file_path.exists():
        console.print(f"[red]Error: File not found: {reply_file}[/red]")
        raise typer.Exit(1)
    
    # Load pending replies
    data = json.loads(file_path.read_text())
    replies = data.get("replies", [])
    
    if not replies:
        console.print("[yellow]No pending replies in file.[/yellow]")
        return
    
    console.print(f"[cyan]PR:[/cyan] #{data.get('pr', {}).get('number', 'unknown')} - {data.get('pr', {}).get('title', '')}")
    console.print(f"[cyan]Pending replies:[/cyan] {len(replies)}\n")
    
    # Filter by comment_id if specified
    if comment_id:
        replies = [r for r in replies if str(r.get("comment_id")) == comment_id]
        if not replies:
            console.print(f"[red]Error: Comment {comment_id} not found.[/red]")
            raise typer.Exit(1)
    
    # Process replies
    sent_replies = []
    for i, reply_data in enumerate(replies, 1):
        if not all_pending and len(replies) > 1:
            # Ask confirmation for each
            console.print(f"\n[bold]回复 {i}/{len(replies)}[/bold]")
            console.print(f"[dim]评论者: {reply_data.get('user')}[/dim]")
            console.print(f"[dim]评论: {reply_data.get('comment_body', '')[:100]}...[/dim]")
            console.print(f"\n[bold]回复内容:[/bold]")
            console.print(Panel(reply_data.get("solution", ""), border_style="green"))
            
            if not dry_run:
                choice = Prompt.ask(
                    "发送此回复?",
                    choices=["y", "n", "e"],
                    default="y"
                )
                if choice == "n":
                    continue
                elif choice == "e":
                    # Edit
                    console.print("[dim]输入新回复 (Ctrl+Z 然后回车结束):[/dim]")
                    lines = []
                    try:
                        while True:
                            line_input = input()
                            lines.append(line_input)
                    except EOFError:
                        pass
                    reply_data["solution"] = "\n".join(lines)
        
        if dry_run:
            console.print(f"[yellow]DRY RUN:[/yellow] Would send reply to comment {reply_data.get('comment_id')}")
            sent_replies.append(reply_data)
        else:
            # Get auth and send
            repo = _detect_repo_from_git()
            platform, token, host = _get_auth_for_repo(repo or "")
            
            if not token:
                console.print("[red]Error: No authentication configured.[/red]")
                raise typer.Exit(1)
            
            # Send reply via API
            result = _send_reply(platform, repo, data["pr"]["number"], reply_data, token, host)
            
            if result:
                console.print(f"[green]✓[/green] Reply sent to comment {reply_data.get('comment_id')}")
                sent_replies.append(reply_data)
            else:
                console.print(f"[red]✗[/red] Failed to send reply to comment {reply_data.get('comment_id')}")
    
    # Summary
    console.print(f"\n[bold]回复完成[/bold]")
    console.print(f"  已发送: {len(sent_replies)} 条")


def _send_reply(platform: str, repo: str, pr_number: int, reply_data: dict, token: str, host: Optional[str]) -> bool:
    """Send reply via API."""
    import httpx
    
    try:
        if platform == "github":
            # For review comments, we need to reply to the specific comment
            # For issue comments, we can just add a new comment
            
            # Try as issue comment first (simpler)
            resp = httpx.post(
                f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments",
                headers={
                    "Authorization": f"token {token}",
                    "Accept": "application/vnd.github.v3+json"
                },
                json={"body": reply_data.get("solution", "")},
                timeout=30
            )
            
            if resp.status_code == 201:
                return True
            else:
                console.print(f"[yellow]GitHub API error: {resp.status_code}[/yellow]")
                return False
        
        elif platform == "gitlab":
            base_url = host or "https://gitlab.com"
            import urllib.parse
            project_id = urllib.parse.quote(repo, safe='')
            
            resp = httpx.post(
                f"{base_url}/api/v4/projects/{project_id}/merge_requests/{pr_number}/notes",
                headers={"PRIVATE-TOKEN": token},
                json={"body": reply_data.get("solution", "")},
                timeout=30
            )
            
            return resp.status_code == 201
        
        elif platform == "gitee":
            owner, project = repo.split("/")
            resp = httpx.post(
                f"https://gitee.com/api/v5/repos/{owner}/{project}/pulls/{pr_number}/comments",
                params={"access_token": token},
                json={"body": reply_data.get("solution", "")},
                timeout=30
            )
            
            return resp.status_code == 201
    
    except Exception as e:
        console.print(f"[red]Error sending reply: {e}[/red]")
        return False
    
    return False


def main():
    """Main entry point."""
    app()


if __name__ == "__main__":
    main()
