#!/usr/bin/env python3
"""
Code Review Kit - Structured code review workflow with multi-language support.

Usage:
    codereview init --lang go
    codereview review <target>
    codereview analyze <issue-id>
    codereview fix [--issues <ids>]
    codereview report [--format html]
    codereview config
    codereview learn
"""

import os
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

app = typer.Typer(
    name="codereview",
    help="Code Review Kit - Structured code review workflow with multi-language support",
    add_completion=False,
)

console = Console()

BANNER = """
  ____          _     ____                  _ _    _ _   
 / ___|___   __| | __| ___|_ __   ___ _ __ | | | _(_) |_ 
| |   / _ \ / _` |/ _`_  / '_ \ / _ \ '_ \| | |/ / | __|
| |__| (_) | (_| | (_| / /| |_) |  __/ | | | |   <| | |_ 
 \____\___/ \__,_|\__,___|_.__/ \___|_| |_|_|_|\_\_|\__|
"""

TAGLINE = "Code Review Kit - Structured code review workflow"


def show_banner():
    """Display the ASCII art banner."""
    banner_lines = BANNER.strip().split('\n')
    colors = ["bright_blue", "cyan", "bright_cyan", "white", "bright_white"]

    styled_banner = Text()
    for i, line in enumerate(banner_lines):
        color = colors[i % len(colors)]
        styled_banner.append(line + "\n", style=color)

    console.print(styled_banner)
    console.print(f"[italic bright_yellow]{TAGLINE}[/italic bright_yellow]")
    console.print()


@app.command()
def init(
    language: str = typer.Option(None, "--lang", "-l", help="Target language (go, python, kotlin, typescript)"),
    ai: str = typer.Option("claude", "--ai", help="AI assistant to use (claude, gemini, copilot)"),
):
    """Initialize code review kit for a project."""
    show_banner()
    
    # Create .review directory
    review_dir = Path.cwd() / ".review"
    review_dir.mkdir(exist_ok=True)
    
    # Create config file
    config_file = review_dir / "config.yaml"
    if not config_file.exists():
        config_content = f"""# Code Review Kit Configuration
# Generated by: codereview init

language: {language or "auto"}
ai_assistant: {ai}

rules:
  severity_threshold: P2  # P0, P1, P2
  enabled_categories:
    - security
    - performance
    - quality
    - style

output:
  format: markdown
  save_history: true
"""
        config_file.write_text(config_content)
        console.print(f"[green]✓[/green] Created {config_file}")
    
    console.print("[green]✓[/green] Code Review Kit initialized successfully!")
    console.print(f"[dim]Config file: {config_file}[/dim]")


@app.command()
def review(
    target: str = typer.Argument(".", help="Files or directories to review"),
    rules: str = typer.Option("default", "--rules", "-r", help="Rules profile"),
    output: str = typer.Option("markdown", "--output", "-o", help="Output format (markdown, json, html)"),
    language: str = typer.Option(None, "--lang", "-l", help="Override language detection"),
):
    """Run code review on target files."""
    show_banner()
    console.print(f"[cyan]Reviewing:[/cyan] {target}")
    console.print(f"[cyan]Rules:[/cyan] {rules}")
    console.print(f"[cyan]Output:[/cyan] {output}")
    console.print()
    
    # TODO: Implement actual review logic
    console.print("[yellow]Review logic to be implemented...[/yellow]")
    console.print("[dim]Use /codereview.review command in your AI assistant for now.[/dim]")


@app.command()
def analyze(
    issue_id: str = typer.Argument(..., help="Issue ID to analyze"),
    deep: bool = typer.Option(False, "--deep", "-d", help="Deep analysis mode"),
):
    """Deep analyze a specific issue."""
    show_banner()
    console.print(f"[cyan]Analyzing issue:[/cyan] {issue_id}")
    
    if deep:
        console.print("[cyan]Mode:[/cyan] Deep analysis")
    
    console.print()
    console.print("[yellow]Analysis logic to be implemented...[/yellow]")


@app.command()
def fix(
    issues: str = typer.Option("all", "--issues", "-i", help="Issues to fix (all, P0, P1, or comma-separated IDs)"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview without applying"),
):
    """Auto-fix issues where possible."""
    show_banner()
    console.print(f"[cyan]Fixing issues:[/cyan] {issues}")
    
    if dry_run:
        console.print("[cyan]Mode:[/cyan] Dry run (no changes)")
    
    console.print()
    console.print("[yellow]Fix logic to be implemented...[/yellow]")


@app.command()
def report(
    format: str = typer.Option("markdown", "--format", "-f", help="Report format (markdown, html, json)"),
    output_file: str = typer.Option(None, "--output", "-o", help="Output file path"),
):
    """Generate report from last review."""
    show_banner()
    console.print(f"[cyan]Report format:[/cyan] {format}")
    
    if output_file:
        console.print(f"[cyan]Output file:[/cyan] {output_file}")
    
    console.print()
    console.print("[yellow]Report generation to be implemented...[/yellow]")


@app.command()
def config():
    """Open or edit configuration."""
    show_banner()
    
    config_file = Path.cwd() / ".review" / "config.yaml"
    if config_file.exists():
        console.print(f"[green]Config file:[/green] {config_file}")
        console.print(f"[dim]Edit this file to customize your review settings.[/dim]")
    else:
        console.print("[yellow]No config file found. Run 'codereview init' first.[/yellow]")


@app.command()
def learn(
    history_dir: str = typer.Option(".review/results", "--history", "-h", help="History directory"),
):
    """Learn from past reviews to improve rules."""
    show_banner()
    console.print(f"[cyan]Learning from:[/cyan] {history_dir}")
    console.print()
    console.print("[yellow]Learning logic to be implemented...[/yellow]")


@app.command()
def check():
    """Check system requirements and installed tools."""
    show_banner()
    
    console.print("[bold]Checking system requirements...[/bold]\n")
    
    # Check Python
    import sys
    console.print(f"[green]✓[/green] Python {sys.version.split()[0]}")
    
    # Check Git
    import shutil
    if shutil.which("git"):
        console.print("[green]✓[/green] Git installed")
    else:
        console.print("[red]✗[/red] Git not found")
    
    # Check language tools
    tools = {
        "go": ["go", "gofmt"],
        "python": ["python", "pylint", "mypy"],
        "node": ["node", "npm", "eslint"],
    }
    
    console.print("\n[bold]Language tools:[/bold]")
    for lang, tool_list in tools.items():
        found = sum(1 for t in tool_list if shutil.which(t))
        total = len(tool_list)
        if found == total:
            console.print(f"[green]✓[/green] {lang}: {found}/{total} tools")
        elif found > 0:
            console.print(f"[yellow]~[/yellow] {lang}: {found}/{total} tools")
        else:
            console.print(f"[dim]○[/dim] {lang}: not installed")


def main():
    """Main entry point."""
    app()


if __name__ == "__main__":
    main()
